# Generated by Django 5.2.3 on 2025-06-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_life_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='composicao',
            field=models.TextField(default='Informação não disponível', help_text='Composição detalhada do produto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='contraindicacao',
            field=models.TextField(default='Consulte um profissional de saúde antes do uso', help_text='Contraindicações e precauções'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='modo_uso',
            field=models.TextField(default='Siga as instruções da embalagem', help_text='Instruções de uso do produto'),
            preserve_default=False,
        ),
    ]
