# Generated by Django 5.2.3 on 2025-06-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_life_app', '0002_produto_composicao_produto_contraindicacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='lancamento',
            field=models.BooleanField(default=False, help_text='Marcar como produto lançamento'),
        ),
        migrations.AddField(
            model_name='produto',
            name='mais_vendido',
            field=models.BooleanField(default=False, help_text='Marcar como produto mais vendido'),
        ),
    ]
